<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IngredientUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientUnitRepository extends EntityRepository
{
}
