# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
      app.admin.user:
                  class: AppBundle\Admin\UserAdmin
                  arguments: [~, AppBundle\Entity\User, SonataAdminBundle:CRUD]
                  tags:
                      - {name: sonata.admin, manager_type: orm, group: User, label: User}

      admin.bistro:
              class: AppBundle\Admin\BistroAdmin
              arguments: [~, AppBundle\Entity\Bistro, ~]
              tags:
                  - { name: sonata.admin, manager_type: orm,  group: Menu, label: Bistro }

      admin.ingredient:
              class: AppBundle\Admin\IngredientAdmin
              arguments: [~, AppBundle\Entity\Ingredient, ~]
              tags:
                  - { name: sonata.admin, manager_type: orm,  group: Menu, label: Ingredient }

      admin.product:
              class: AppBundle\Admin\ProductAdmin
              arguments: [~, AppBundle\Entity\Product, ~]
              tags:
                  - { name: sonata.admin, manager_type: orm,  group: Menu, label: Product }

      admin.product.ingredient:
              class: AppBundle\Admin\ProductIngredientAdmin
              arguments: [~, AppBundle\Entity\ProductIngredient, ~]
              tags:
                  - { name: sonata.admin, manager_type: orm,  group: Menu, label: Product Ingredient }
      admin.product.bistro.worker:
              class: AppBundle\Admin\BistroWorkerAdmin
              arguments: [~, AppBundle\Entity\BistroWorker, ~]
              tags:
                  - { name: sonata.admin, manager_type: orm,  group: Menu, label: Bistro Worker }
